### PR TITLE
Readability improvement of Connection::connect

### LINKED ISSUE #57: Call $this->receive() twice in Connection::connect()
Maybe my misunderstanding of the Nats protocol, but why did we call `$this->receive();` twice in Connection::connect() ?

```
public function connect($timeout = null)
{
    $this->timeout = $timeout;
    $this->streamSocket = $this->getStream($this->options->getAddress(), $timeout);
    $msg = 'CONNECT '.$this->options;
    $this->send($msg);

    $response = $this->receive();

    $this->ping();
    $response = $this->receive();

    if ($response !== "PONG") {
        if (strpos($response, '-ERR')!== false) {
            throw new \Exception("Failing connection: $response");
        }
    }
}
```

### PR DESCRIPTION
**Pull request by anthonysterling**
- Added a private isErrorResponse method to check if response is of -ERR
- Created some Exception factory methods to centralise/standardise Exceptions and their messages

Fixes #57

### CODE REVIEW

File: src/Nats/Connection.php [hunk 1]
```diff
@@ -239,16 +239,16 @@ public function connect($timeout = null)
...
-        if (strpos($connect_response, '-ERR')!== false) {
-            throw new \Exception("Failing connection: $connect_response");
+
+        if ($this->isErrorResponse($connect_response)) {
+            throw Exception::forFailedConnection($connect_response);
         }
 
         $this->ping();
         $ping_response = $this->receive();
-        if ($ping_response !== "PONG") {
```
Comment (anthonysterling) [inline src/Nats/Connection.php]: I removed this as we could just check for `-ERR` and get the expected behaviour.

**Comment by dfeyer** [comment]
By reading the code look OK, @repejota what do you think ?

I can test this PR tomorrow more in details

**Comment by repejota** [comment]
Thanks!!!!
